services:
  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./debug/:/data
    ports:
      - 8025:8025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_TLS_CERT: /data/certs/cert.pem
      MP_SMTP_TLS_KEY: /data/certs/key.pem
      MP_SMTP_REQUIRE_STARTTLS: true
    networks:
      - backend
    profiles:
      - debug

  server:
    environment:
      GIN_MODE:
      SMTP_HOST: mailpit
      SMTP_PORT: "1025"
      SMTP_USER: debug
      SMTP_PASS: debug
      SMTP_FROM: debug@weather.com
    depends_on:
      - mailpit
    profiles:
      - debug
