services:
  db:
    image: postgres:17-alpine3.21
    env_file:
      .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - backend

  server:
    env_file:
      .env
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server"]
    environment:
      POSTGRES_HOST: db
      HOST: ${HOST}
      PORT: ${PORT}
      WEATHERAPI_KEY: ${WEATHERAPI_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${SMTP_FROM}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
